apiVersion: template.openshift.io/v1
kind: TemplateInstance
metadata:
  name: pi
spec:
  template:
    metadata:
      annotations:
        description: xxxxxx
      name: pi
      namespace: openshift 
    objects:
    - apiVersion: batch/v1
      kind: Job
      metadata:
        annotations:
          template.alpha.openshift.io/wait-for-ready: 'true'
        name: pi
      spec:
        completions: 1
        parallelism: 1
        template:
          metadata:
            name: pi
          spec:
            containers:
            - command:
              - perl
              - -Mbignum=bpi
              - -wle
              - print bpi(2000)
              image: perl
              name: pi
            restartPolicy: OnFailure
